- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.ssh
    state: directory
    mode: '0700'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Generate SSH key
  ansible.builtin.command: ssh-keygen -t rsa -b 2048 -f /home/{{ ansible_user }}/.ssh/id_rsa -N ""
  args:
    creates: /home/{{ ansible_user }}/.ssh/id_rsa

- name: Ensure correct permissions on the SSH key
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.ssh/id_rsa
    mode: '0600'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Ensure correct permissions on the SSH public key
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.ssh/id_rsa.pub
    mode: '0644'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Read the generated public key
  ansible.builtin.slurp:
    src: /home/{{ ansible_user }}/.ssh/id_rsa.pub
  register: public_key

- name: Add SSH public key to authorized_keys
  ansible.builtin.lineinfile:
    path: /home/{{ ansible_user }}/.ssh/authorized_keys
    line: "{{ public_key['content'] | b64decode }}"
    create: yes
    mode: '0600'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

