---
- name: Disable host key checking
  hosts: all
  tasks:
    - name: Disable host key checking for this session
      set_fact:
        ANSIBLE_HOST_KEY_CHECKING: False

- name: Become sudo users in all nodes
  hosts: all
  remote_user: root
  become: yes
  vars:
    ansible_become_password: "{{ ansible_password }}"
  roles:
    - sudo-user
    
- name: Generate SSH keys on nodes
  hosts: all
  become: yes
  vars:
    ansible_become_password: "{{ ansible_password }}"
  roles:
    - key-generate

- name: Transfer keys to the nodes 1
  hosts: node1
  become: yes
  remote_user: "{{ ansible_user }}"
  vars:
    ansible_become_password: "{{ ansible_password }}"
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"
  roles:
    - transfer-key

- name: Transfer keys to the nodes 2
  hosts: node2
  become: yes
  remote_user: "{{ ansible_user }}"
  vars:
    ansible_become_password: "{{ ansible_password }}"
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"
  roles:
    - transfer-key1

- name: Transfer keys to the nodes 3
  hosts: node3
  become: yes
  remote_user: "{{ ansible_user }}"
  vars:
    ansible_become_password: "{{ ansible_password }}"
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"
  roles:
    - transfer-key-2