---
- name: Generate SSH keys on nodes
  hosts: all
  become: yes
  
  roles:
    - key-generate

- name: Transfer keys to the nodes 1
  hosts: node1
  become: yes
  remote_user: kube-spray
  vars:
    ansible_ssh_private_key_file: "{{ inventory_dir }}/key1"
  roles:
    - transfer-key

- name: Transfer keys to the nodes 2
  hosts: node2
  become: yes
  remote_user: worker1
  vars:
    ansible_ssh_private_key_file: "{{ inventory_dir }}/key2"
  roles:
    - transfer-key1

- name: Become sudo users in all nodes
  hosts: all
  become: yes
  roles:
    - sudo-user

- name: Install Python
  hosts: node1
  become: yes
  roles:
    - python

- name: KubeSpray Cluster Setup
  hosts: node1
  become: yes
  
  roles:
    - kube-spray-setup