---
- name: Generate SSH keys on nodes
  hosts: node1
  become: yes
  
  roles:
    - key-generate

- name: Transfer keys to the nodes
  hosts: all
  become: false
  roles:
    - transfer-key
