---
- name: Generate SSH keys on nodes
  hosts: all
  become: yes
  
  roles:
    - key-generate

# - name: Transfer keys to the nodes
#   hosts: all
#   become: false
#   roles:
#     - transfer-key
