---
- name: Become sudo users in all nodes
  hosts: all
  remote_user: root
  become: yes
  vars:
    ansible_become_password: "{{ ansible_password }}"
  roles:
    - sudo-user

- name: Install Python
  hosts: node1
  become: yes
  vars:
    ansible_become_password: "{{ ansible_password }}"
  roles:
    - python

- name: KubeSpray Cluster Setup
  hosts: node1
  become: yes
  vars:
    target_user: "{{ ansible_user }}" 
    ansible_become_password: "{{ ansible_password }}"
    CONFIG_FILE: "/tmp/kubespray/inventory/my-cluster/hosts.yml"
  roles:
    - kube-spray-setup