#!/bin/bash

# Read IPs from the file generated by the Ansible playbook
IPS=$(cat machine.yml)

# Loop through each IP and run the SSH commands
for IP in $IPS; do
  ssh -T kube-spray@$IP << 'EOF'

  # Switch to root user
  sudo su << 'EOSU'

  # Navigate to the /root directory
  cd /root

  # Generate SSH key, automatically confirming overwrite if key already exists
  yes y | ssh-keygen -t rsa -N "" -f /root/.ssh/id_rsa

  # Display the generated public key
  cat /root/.ssh/id_rsa.pub

  # Add the public key to authorized_keys
  cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys

  EOSU
  EOF
done
