- name: Install Python
  package:
    name: python3
    state: present
- name: Install Pip
  package:
    name: python3-pip
    state: present

- name: Install EPEL repository (for RHEL/CentOS systems)
  ansible.builtin.yum:
    name: epel-release
    state: present
  when: ansible_os_family == "RedHat"

- name: Ensure Python 3 and setuptools are installed
  package:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - python3-setuptools

- name: Ensure pip3 is installed
  command: python3 -m ensurepip
  args:
    creates: /usr/local/bin/pip3

- name: Upgrade pip3
  pip:
    name: pip
    state: latest
    executable: pip3

- name: Upgrade pip and setuptools
  command: python3 -m pip install --upgrade pip setuptools