- name: Install git
  package:
    name: git
    state: present


- name: Ensure primary DNS settings are correct
  lineinfile:
    path: /etc/resolv.conf
    line: "nameserver 8.8.8.8"
    state: present

- name: Ensure secondary DNS settings are correct
  lineinfile:
    path: /etc/resolv.conf
    line: "nameserver 8.8.4.4"
    state: present

- name: Test connectivity to GitHub
  command: ping -c 4 github.com
  register: ping_result
  ignore_errors: true

- name: Fail if unable to reach GitHub
  fail:
    msg: "Unable to reach GitHub. Please check network settings."
  when: ping_result.rc != 0

- name: Clone the Kubespray repository
  git:
    repo: "https://github.com/kubernetes-sigs/kubespray.git"
    dest: "/tmp/kubespray"
    version: "master"
    force: yes


- name: Install the required Python packages
  pip:
    name:
      - requests
      - jinja2
      - pyyaml
      - netaddr
    state: present

- name: Install requirements
  pip:
    requirements: /tmp/kubespray/requirements.txt

- name: Copy inventory directory
  ansible.builtin.command: cp -rfp /tmp/kubespray/inventory/sample /tmp/kubespray/inventory/my-cluster

- name: Install requirements
  pip:
    requirements: /tmp/kubespray/contrib/inventory_builder/requirements.txt

- name: Run inventory script
  shell: |
    CONFIG_FILE=/tmp/kubespray/inventory/my-cluster/hosts.yml python3 /tmp/kubespray/contrib/inventory_builder/inventory.py {{ IPS | join(' ') }}
  args:
    chdir: "/tmp/kubespray"  # Update this path to the location of your kube-spray



- name: Execute kubespray playbook for cluster setup
  shell: |
    ansible-playbook -i inventory/my-cluster/hosts.yml cluster.yml
  args:
    chdir: /tmp/kubespray

- name: Create .kube directory
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory
    mode: '0755'

- name: Copy Kubernetes admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ ansible_env.HOME }}/.kube/config"
    owner: root
    group: root
    mode: '0644'
    remote_src: yes

- name: Change ownership of kube config
  file:
    path: "{{ ansible_env.HOME }}/.kube/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  become: true


