- name: Install git
  package:
    name: git
    state: present

- name: Clone the Kubespray repository
  git:
    repo: https://github.com/kubernetes-incubator/kubespray.git
    dest: /tmp/kubespray
    version: master

- name: Install the required Python packages
  pip:
    name:
      - requests
      - jinja2
      - pyyaml
      - netaddr
    state: present


- name: Install requirements
  pip:
    requirements: /tmp/kubespray/requirements.txt

- name: Copy inventory directory
  ansible.builtin.command: cp -rfp /tmp/kubespray/inventory/sample /tmp/kubespray/inventory/my-cluster

- name: Install requirements
  pip:
    requirements: /tmp/kubespray/contrib/inventory_builder/requirements.txt


- name: Run inventory script
  shell: |
    CONFIG_FILE=/tmp/kubespray/inventory/my-cluster/hosts.yml python3 /tmp/kubespray/contrib/inventory_builder/inventory.py {{ IPS | join(' ') }}
  args:
    chdir: "/tmp/kubespray"  # Update this path to the location of your kube-spray


- name: Add ansible_user and ansible_ssh_private_key_file to node1
  ansible.builtin.blockinfile:
    path: /tmp/kubespray/inventory/my-cluster/hosts.yml
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
          ansible_user: kube-spray
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
    insertafter: '^      access_ip: 172.25.204.49$'

- name: Add ansible_user and ansible_ssh_private_key_file to node2
  ansible.builtin.blockinfile:
    path: /tmp/kubespray/inventory/my-cluster/hosts.yml
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
          ansible_user: worker1
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
    insertafter: '^      access_ip: 172.25.204.50$'

- name: Add ansible_user and ansible_ssh_private_key_file to node3
  ansible.builtin.blockinfile:
    path: /tmp/kubespray/inventory/my-cluster/hosts.yml
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
          ansible_user: worker2
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
    insertafter: '^      access_ip: 172.25.204.51$'

- name: Remove node2 from kube_control_plane
  ansible.builtin.lineinfile:
    path: /tmp/kubespray/inventory/my-cluster/hosts.yml
    regexp: '^        node2:$'
    state: absent


- name: Execute kubespray playbook for cluster setup
  command: ansible-playbook -i /tmp/kubespray/inventory/my-cluster/hosts.yml cluster.yml
  args:
    chdir: /tmp/kubespray

- name: Create .kube directory
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory
    mode: '0755'

- name: Copy Kubernetes admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ ansible_env.HOME }}/.kube/config"
    owner: root
    group: root
    mode: '0644'
    remote_src: yes

- name: Change ownership of kube config
  file:
    path: "{{ ansible_env.HOME }}/.kube/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  become: true