- name: Install git
  package:
    name: git
    state: present

- name: Clone the Kubespray repository
  git:
    repo: https://github.com/kubernetes-incubator/kubespray.git
    dest: /tmp/kubespray
    version: master

- name: Install the required Python packages
  pip:
    name:
      - requests
      - jinja2
      - pyyaml
      - netaddr
    state: present


- name: Install requirements
  pip:
    requirements: /tmp/kubespray/requirements.txt

- name: Copy inventory directory
  ansible.builtin.command: cp -rfp /tmp/kubespray/inventory/sample /tmp/kubespray/inventory/my-cluster

- name: Install requirements
  pip:
    requirements: /tmp/kubespray/contrib/inventory_builder/requirements.txt


- name: Ensure ips.yml exists
  ansible.builtin.stat:
    path: "{{ playbook_dir }}/ips.yml"
  delegate_to: localhost
  become: false
  register: ips_file_stat

- name: Run inventory script
  command: python3 contrib/inventory_builder/inventory.py "{{ IPS | join(' ') }}"
  args:
    chdir: "/tmp/kubespray"  # Update this path to the location of your kube-spray
  register: inventory_result

- name: Save inventory file
  copy:
    content: "{{ inventory_result.stdout }}"
    dest: "{{ CONFIG_FILE }}"




- name: Execute kubespray playbook for cluster setup
  command: ansible-playbook -i /tmp/kubespray/inventory/my-cluster/hosts.yml cluster.yml
  args:
    chdir: /tmp/kubespray

- name: Create .kube directory
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory
    mode: '0755'

- name: Copy Kubernetes admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ ansible_env.HOME }}/.kube/config"
    owner: root
    group: root
    mode: '0644'
    remote_src: yes

- name: Change ownership of kube config
  file:
    path: "{{ ansible_env.HOME }}/.kube/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  become: true