- name: Install git
  package:
    name: git
    state: present

- name: Clone the Kubespray repository
  git:
    repo: https://github.com/kubernetes-incubator/kubespray.git
    dest: /tmp/kubespray
    version: master

- name: Install the required Python packages
  pip:
    name:
      - requests
      - jinja2
      - pyyaml
      - netaddr
    state: present


- name: Install requirements
  pip:
    requirements: /tmp/kubespray/requirements.txt

- name: Copy inventory directory
  ansible.builtin.command: cp -rfp /tmp/kubespray/inventory/sample /tmp/kubespray/inventory/my-cluster

- name: Install requirements
  pip:
    requirements: /tmp/kubespray/contrib/inventory_builder/requirements.txt


- name: Run inventory script
  shell: |
    CONFIG_FILE=/tmp/kubespray/inventory/my-cluster/hosts.yml python3 /tmp/kubespray/contrib/inventory_builder/inventory.py {{ IPS | join(' ') }}
  args:
    chdir: "/tmp/kubespray"  # Update this path to the location of your kube-spray

- name: Print file contents before modification
  command: cat /tmp/kubespray/inventory/my-cluster/hosts.yml
  register: cat_result_before
  changed_when: false

- debug:
    var: cat_result_before.stdout_lines

- name: Add a line before a specific line
  lineinfile:
    path: /tmp/kubespray/inventory/my-cluster/hosts.yml
    line: '      ansible_user: kube-spray'
    insertafter: '      access_ip: 172.25.204.49'
  register: result_1
- debug:
    var: result_1

- name: Add a line before a specific line
  lineinfile:
    path: /tmp/kubespray/inventory/my-cluster/hosts.yml
    line: '      ansible_ssh_private_key_file: ~/.ssh/id_rsa'
    insertafter: '      ansible_user: kube-spray'
  register: result_2

- debug:
        var: result_2

- name: Add a line before a specific line
  lineinfile:
    path: /tmp/kubespray/inventory/my-cluster/hosts.yml
    line: '      ansible_user: worker1'
    insertafter: '      access_ip: 172.25.204.50'
  register: result_3

- debug:
    var: result_3

- name: Add a line before a specific line
  lineinfile:
    path: /tmp/kubespray/inventory/my-cluster/hosts.yml
    line: '      ansible_ssh_private_key_file: ~/.ssh/id_rsa'
    insertafter: '      ansible_user: worker1'
  register: result_4

- debug:
    var: result_4


- name: Add a line after a specific line
  lineinfile:
    path: /tmp/kubespray/inventory/my-cluster/hosts.yml
    line: '      ansible_user: worker2'
    insertafter: '      access_ip: 172.25.204.51'

- name: Add a line after a specific line
  lineinfile:
    path: /tmp/kubespray/inventory/my-cluster/hosts.yml
    line: '      ansible_ssh_private_key_file: ~/.ssh/id_rsa'
    insertbefore: '      ansible_user: worker2'

- name: Remove node2 from kube_control_plane
  ansible.builtin.lineinfile:
    path: /tmp/kubespray/inventory/my-cluster/hosts.yml
    regexp: '^        node2:$'
    state: absent

- name: Print file contents after modification
  command: cat /tmp/kubespray/inventory/my-cluster/hosts.yml
  register: cat_result_after
  changed_when: false

- debug:
    var: cat_result_after.stdout_lines


# - name: Execute kubespray playbook for cluster setup
#   command: ansible-playbook -i /tmp/kubespray/inventory/my-cluster/hosts.yml cluster.yml
#   args:
#     chdir: /tmp/kubespray

# - name: Create .kube directory
#   file:
#     path: "{{ ansible_env.HOME }}/.kube"
#     state: directory
#     mode: '0755'

# - name: Copy Kubernetes admin.conf to user's kube config
#   copy:
#     src: /etc/kubernetes/admin.conf
#     dest: "{{ ansible_env.HOME }}/.kube/config"
#     owner: root
#     group: root
#     mode: '0644'
#     remote_src: yes

# - name: Change ownership of kube config
#   file:
#     path: "{{ ansible_env.HOME }}/.kube/config"
#     owner: "{{ ansible_user }}"
#     group: "{{ ansible_user }}"
#     mode: '0644'
#   become: true