- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.ssh
    state: directory
    mode: '0700'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Accept host key for node2
  ansible.builtin.shell: "ssh-keyscan -H {{ node1.ansible_host }} >> ~/.ssh/known_hosts"
  when: inventory_hostname == 'node2'

- name: Add SSH public key to authorized_keys
  ansible.builtin.lineinfile:
    path: "/home/{{ ansible_user }}/.ssh/authorized_keys"
    line: "{{ lookup('file', '/home/node1.' ~ ansible_user ~ '/.ssh/id_rsa.pub') }}"
    create: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
  vars:
    ansible_ssh_private_key_file: "{{ hostvars[inventory_hostname].ansible_ssh_private_key_file }}"
  when: inventory_hostname == 'node2'
